name = "Irl-events"
main = "src/worker.ts"
compatibility_date = "2025-10-03"
workers_dev = true

# Serve static files from Vite build output via binding "ASSETS"
assets = { directory = "dist", binding = "ASSETS" }

# When ready to map to a real domain, uncomment and edit:
# routes = [
#   # Map apex and www to the Worker (SPA)
#   { pattern = "irlevents.fun", custom_domain = true },
#   { pattern = "www.irlevents.fun", custom_domain = true },
# ]
